# Generated by Django 2.2.7 on 2021-08-31 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('cost_per_item', models.FloatField(blank=True, default=0, null=True)),
                ('stock_quantity', models.IntegerField(blank=True, default=0, null=True)),
                ('volume', models.CharField(max_length=20, null=True)),
            ],
            options={
                'db_table': 'Product_Info',
            },
        ),
    ]
