# Generated by Django 2.2.7 on 2021-09-01 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0002_usermodel'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='usermodel',
            table='UserModel_Info',
        ),
    ]
