# Generated by Django 2.2.7 on 2021-09-01 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0003_auto_20210901_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='user_token',
            field=models.CharField(max_length=200),
        ),
    ]
