# Generated by Django 2.2.7 on 2021-09-01 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0004_auto_20210901_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='user_token',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
