# Generated by Django 2.2.7 on 2021-09-03 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0007_auto_20210902_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='user_token',
            field=models.CharField(default=1, max_length=200, unique=True),
            preserve_default=False,
        ),
    ]
