# Generated by Django 2.2.7 on 2021-09-03 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_app', '0008_auto_20210903_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='user_token',
            field=models.CharField(max_length=200),
        ),
    ]
